"""Legal-silo elevation converter (round 8).
Carries each live legal document VERBATIM into the 11ty factory:
- the entire .legal-doc block (header, meta, plain-language summary, TOC,
  numbered sections) — markup, IDs, and text untouched; the live BEM class
  vocabulary is adopted as a tokenized EXTENSION in 07-extensions.css
- title + meta description from the live head (BSS artifact titles dropped
  — TODO 4)
- page-specific JSON-LD nodes (everything except the global Organization
  graph, which base.njk injects from schemaGlobal.json) → <name>.11tydata.js
Emits src/legal/<name>.njk (JSON front matter) + src/legal/<name>.11tydata.js.
Usage: python _build/scripts/port_legal.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src" / "legal"
OUT.mkdir(parents=True, exist_ok=True)

PAGES = [
    # (live file, permalink, slug, breadcrumb current label)
    ("legal/disclaimer/index.html", "/legal/disclaimer/", "disclaimer", "Disclaimer"),
    ("legal/dpa/index.html", "/legal/dpa/", "dpa", "Data Processing Terms"),
    ("legal/privacy-policy/index.html", "/legal/privacy-policy/", "privacy", "Privacy Policy"),
    ("legal/terms/index.html", "/legal/terms/", "terms", "Terms of Service"),
]

for live, permalink, slug, crumb in PAGES:
    html = (ROOT / live).read_text(encoding="utf-8")

    # real title: single-line, not the BSS artifact, not the site-default
    # duplicate; the page's real meta description directly follows it
    tm = next(m for m in re.finditer(r"<title>([^<\n]+)</title>", html)
              if m.group(1).strip() != "BSS-1-11ty"
              and not m.group(1).startswith("A Modern Accounting Platform"))
    title = tm.group(1).strip()
    desc = re.search(
        r'<meta name="description" content="([^"]*)"', html[tm.end():]).group(1)

    sec = re.search(
        r'(<section class="section section--legal-doc"[^>]*>.*?)\s*</main>',
        html, re.S)
    block = sec.group(1).rstrip()
    # the block ends with the section's own </section>; keep through it
    last = block.rfind("</section>")
    block = block[: last + len("</section>")]

    # page-specific JSON-LD: every block that is NOT the global graph
    page_nodes = []
    for m in re.findall(r'<script type="application/ld\+json">(.*?)</script>',
                        html, re.S):
        node = json.loads(m)
        graph = node.get("@graph", [node])
        types = {t for g in graph for t in
                 (g.get("@type") if isinstance(g.get("@type"), list)
                  else [g.get("@type")])}
        if "Organization" in types or "WebSite" in types:
            continue  # global graph — injected from schemaGlobal.json
        page_nodes.append(node)

    fm = {
        "layout": "layouts/t-mofu.njk",
        "permalink": permalink,
        "slug": slug,
        "tierClass": "section--tier-guide",
        "bodyClass": "page--legal",
        "title": title,
        "description": desc,
        "breadcrumb": [{"name": "Home", "href": "/"}, {"name": crumb}],
    }
    njk = "---json\n" + json.dumps(fm, indent=2, ensure_ascii=False) + "\n---\n\n" + block + "\n"
    (OUT / f"{slug}.njk").write_text(njk, encoding="utf-8")

    if len(page_nodes) == 1:
        graph_js = json.dumps(page_nodes[0], indent=2, ensure_ascii=False)
    else:
        graph_js = json.dumps(
            {"@context": "https://schema.org",
             "@graph": [g for n in page_nodes for g in n.get("@graph", [n])]},
            indent=2, ensure_ascii=False)
    js = ("/* " + permalink + " page JSON-LD — extracted VERBATIM from the live\n"
          " * page at elevation (round 8); global Organization graph excluded\n"
          " * (base.njk injects schemaGlobal.json). GENERATED by\n"
          " * _build/scripts/port_legal.py — edit the live source of truth,\n"
          " * not this file, until cutover. */\n"
          "module.exports = { pageGraph: " + graph_js + " };\n")
    (OUT / f"{slug}.11tydata.js").write_text(js, encoding="utf-8")

    print(f"{permalink}  title={title[:60]!r}  sections="
          f"{block.count('legal-doc__section')}  pageNodes={len(page_nodes)}")
print("done — review emitted files before building")
