/* Blog categories (round 87, NEW article type). Single source of truth for the
 * 8 category pages (generated by pagination from src/blog/category.njk) and the
 * hub's category nav. `slug` MUST match the tag each post carries, so 11ty's
 * auto-collection collections[slug] holds that category's posts. */
module.exports = [
  { slug: "quickbooks", label: "QuickBooks", blurb: "Getting the most out of QuickBooks — setup, features, mistakes to avoid, and Online vs Desktop — from a Certified ProAdvisor team." },
  { slug: "bookkeeping", label: "Bookkeeping", blurb: "How clean books actually get kept: the monthly close, cleanup, catch-up, and knowing when to bring in help." },
  { slug: "accounting", label: "Accounting", blurb: "The fundamentals every owner should understand — bookkeeping vs accounting, the core reports, and what your numbers are telling you." },
  { slug: "payroll", label: "Payroll", blurb: "Running payroll correctly: worker classification, multi-state compliance, deadlines, and the year-end forms that trip people up." },
  { slug: "taxes", label: "Taxes", blurb: "How to keep your books tax-ready and work well with your CPA. We don't file taxes — we make tax season painless. Not tax advice." },
  { slug: "business-finance", label: "Business Finance", blurb: "Cash flow, margins, break-even, and runway — the financial literacy that helps owners make better decisions." },
  { slug: "ai-and-accounting", label: "AI & Accounting", blurb: "An honest, ground-level look at where AI helps with bookkeeping and accounting — and where it quietly gets things wrong." },
  { slug: "partner-spotlight", label: "Partner Spotlight", blurb: "Our accountant partner program — how it works, who it's for, and how independent firms collaborate with TechBrot." },
];
